// Simple i18n dictionary for EN/ES
window.I18N = {
  en: {
    "nav.home":"Home","nav.products":"Products","nav.brands":"Brands","nav.whyus":"Why Us","nav.resources":"Resources","nav.contact":"Contact",
    "hero.h1":"Hard-to-find spare parts for legacy automation systems",
    "hero.sub":"We source obsolete and current-line industrial automation components so your production lines stay online, not on hold.",
    "hero.btnQuote":"Get a fast quote","hero.btnUpload":"Upload your parts list",
    "trust.one":"Obsolete & legacy specialists","trust.two":"Europe-wide and global sourcing","trust.three":"Warranty on every part supplied",
    "who.title":"Built for maintenance, engineering and purchasing teams",
    "who.p":"When a critical PLC, drive or HMI fails on a legacy line, every minute counts. UptimeLegacy helps maintenance, engineering and purchasing teams quickly locate obsolete and hard-to-find automation parts, compare options and get reliable replacements on site before downtime spirals into lost production.",
    "brands.title":"Trusted brands we support",
    "brands.intro":"We work with a broad network of partners to find both current-line and obsolete parts from leading industrial automation brands. Whether you need a legacy CPU, a discontinued drive or a replacement HMI, we can help you source the right OEM component.",
    "brands.viewAll":"View all brands →",
    "categories.title":"Legacy and current-line automation categories",
    "categories.intro":"UptimeLegacy covers the full range of industrial automation spares for production and process plants. From control to motion to safety, we help you keep legacy systems running safely and reliably.",
    "cat.plc.title":"PLCs & I/O modules","cat.plc.body":"Legacy and current CPU modules, input/output cards and expansion units",
    "cat.hmi.title":"HMIs & industrial PCs","cat.hmi.body":"Operator panels, touch screens and rugged industrial computers",
    "cat.drives.title":"Drives & inverters","cat.drives.body":"AC/DC drives, servo drives and frequency inverters for motion control",
    "cat.motors.title":"Motors, servos & encoders","cat.motors.body":"Industrial motors, servo motors and position feedback encoders",
    "cat.cnc.title":"CNC & motion controllers","cat.cnc.body":"CNC control systems and motion control boards for legacy machines",
    "cat.safety.title":"Safety & field devices","cat.safety.body":"Safety relays, emergency stops and industrial field sensors",
    "cat.power.title":"Power supplies & control","cat.power.body":"Industrial power supplies, transformers and control components",
    "cat.all.title":"Browse all categories","cat.all.body":"Complete range of automation spare parts and components",
    "how.title":"How UptimeLegacy helps you avoid downtime",
    "how.intro":"Whether you are facing an unexpected breakdown or planning for upcoming obsolescence, UptimeLegacy gives you a single point of contact to source the right parts, at the right time and condition, to protect your uptime.",
    "how.c1.title":"Emergency breakdown sourcing","how.c1.body":"When a line is down, we move fast. Share your part numbers or upload your list, and our team will search our network for available stock, compatible alternatives and express shipping options.",
    "how.c2.title":"Stock replenishment & maintenance planning","how.c2.body":"Build the right spare parts strategy for your installed base. We help you identify critical spares, quote stock packages and manage replenishment for scheduled maintenance.",
    "how.c3.title":"Obsolescence & lifecycle management","how.c3.body":"Plan ahead for end-of-life components. We support last-time buy decisions, identify form-fit-function replacements and propose migration paths where possible.",
    "how.c4.title":"Exchange, repair & retrofit options","how.c4.body":"Extend the life of your automation assets. Depending on your part and budget, we can offer exchange units, tested refurbished options or repair routes via trusted partners.",
    "how.cta":"Learn more about how we help →",
    "why.title":"Why maintenance teams choose UptimeLegacy",
    "why.b1.title":"Legacy-first focus","why.b1.body":"We specialise in obsolete and legacy industrial automation rather than general MRO. That means faster answers and more realistic options when manufacturers have stopped supporting your hardware.",
    "why.b2.title":"Global sourcing network","why.b2.body":"We tap into stock across Europe and beyond to locate hard-to-find parts, often with shorter lead times than the original manufacturer.",
    "why.b3.title":"Quality and warranty","why.b3.body":"Every part we supply is tested or quality checked and covered by warranty, with clear conditions for new, refurbished, exchange and repaired units.",
    "why.b4.title":"Single point of contact","why.b4.body":"One team handles your RFQs, sourcing, logistics and after-sales questions, so you don’t have to chase multiple suppliers.",
    "stories.title":"Real results for real production lines",
    "stories.s1.title":"Automotive supplier – legacy drive failure","stories.s1.body":"A legacy drive failure threatened to stop an automotive line for several days. UptimeLegacy sourced a compatible unit from our network, arranged express shipment and helped the maintenance team get the line running again within 24 hours.",
    "stories.s2.title":"Food & beverage – obsolete PLC platform","stories.s2.body":"A food processor was running an obsolete PLC platform with limited spare coverage. We helped build a critical spares list, supply stock and identify migration options to reduce the risk of unplanned downtime.",
    "stories.cta":"View more case studies →",
    "resources.title":"Resources for maintenance & engineering teams",
    "resources.intro":"Share these guides with your maintenance, engineering and purchasing teams to improve how you plan and source spares for legacy automation.",
    "res.r1.title":"Legacy Automation Spare Parts Guide","res.r1.body":"How to identify critical components, assess risk and build the right spare parts strategy for older systems.","res.r1.cta":"Download the guide →",
    "res.r2.title":"5-Step Guide to Sourcing Obsolete Parts","res.r2.body":"A practical checklist to speed up RFQs, compare offers and avoid common pitfalls when dealing with obsolete components.","res.r2.cta":"Get the checklist →",
    "res.r3.title":"UptimeLegacy Line Card","res.r3.body":"Overview of brands, product categories and services available through UptimeLegacy.","res.r3.cta":"Request the line card →",
    "insights.title":"Latest insights","insights.intro":"Short, practical articles for engineers, maintenance managers and buyers working with legacy automation systems.",
    "insights.i1.title":"How to reduce the risk of downtime on legacy PLC systems","insights.i1.body":"Many plants still rely on PLC platforms introduced decades ago. Here are the key steps to protect your uptime while you plan migrations.",
    "insights.i2.title":"Understanding spare parts condition options","insights.i2.body":"New, refurbished, exchange or repair – what are the differences and how to choose the right option for your needs.",
    "insights.i3.title":"Building an effective legacy parts inventory strategy","insights.i3.body":"Practical advice on how to balance cost and risk when stocking spare parts for aging automation systems.",
    "insights.read":"Read article →","insights.all":"View all articles →",
    "contact.title":"Need urgent support with a failed part?","contact.p":"Share your part number, upload your list or call our team for immediate assistance. We’ll respond quickly with availability, options and lead times.","contact.cta1":"Request a quote","contact.cta2":"Call our team",
    "footer.products":"Products","footer.p1":"PLCs & I/O","footer.p2":"HMIs & PCs","footer.p3":"Drives & Inverters","footer.p4":"Motors & Servos","footer.p5":"CNC Controllers","footer.p6":"Safety Devices",
    "footer.brands":"Brands","footer.resources":"Resources","footer.r1":"Guides & Checklists","footer.r2":"Blog & Insights","footer.r3":"Case Studies","footer.r4":"FAQ","footer.r5":"Support",
    "footer.company":"Company","footer.c1":"About UptimeLegacy","footer.c2":"Contact Us","footer.c3":"Privacy Policy","footer.c4":"Terms & Conditions","footer.c5":"Cookie Policy",
    "footer.copy":"© 2024 UptimeLegacy. All rights reserved. | No downtime for legacy lines"
  },
  es: {
    "nav.home":"Inicio","nav.products":"Productos","nav.brands":"Marcas","nav.whyus":"Por qué nosotros","nav.resources":"Recursos","nav.contact":"Contacto",
    "hero.h1":"Repuestos difíciles para sistemas de automatización legacy",
    "hero.sub":"Localizamos componentes obsoletos y de línea actual para que tus líneas de producción sigan operativas, no en espera.",
    "hero.btnQuote":"Pide una cotización rápida","hero.btnUpload":"Sube tu lista de repuestos",
    "trust.one":"Especialistas en obsoletos y legacy","trust.two":"Abastecimiento en Europa y a nivel global","trust.three":"Garantía en cada pieza suministrada",
    "who.title":"Pensado para mantenimiento, ingeniería y compras",
    "who.p":"Cuando falla un PLC, un variador o una HMI en una línea legacy, cada minuto cuenta. UptimeLegacy ayuda a mantenimiento, ingeniería y compras a localizar con rapidez repuestos obsoletos y difíciles, comparar opciones y conseguir reemplazos fiables antes de que el paro se convierta en pérdida de producción.",
    "brands.title":"Marcas que soportamos",
    "brands.intro":"Trabajamos con una amplia red de socios para encontrar repuestos de línea actual y obsoletos de las principales marcas de automatización industrial. Ya sea una CPU legacy, un variador descatalogado o una HMI de reemplazo, te ayudamos a conseguir el componente OEM adecuado.",
    "brands.viewAll":"Ver todas las marcas →",
    "categories.title":"Categorías de automatización legacy y de línea actual",
    "categories.intro":"UptimeLegacy cubre todo el rango de repuestos de automatización para plantas de proceso y producción. Desde control hasta motion y seguridad, te ayudamos a mantener los sistemas legacy seguros y operativos.",
    "cat.plc.title":"PLCs y módulos I/O","cat.plc.body":"CPUs legacy y actuales, tarjetas de entradas/salidas y módulos de expansión",
    "cat.hmi.title":"HMIs y PCs industriales","cat.hmi.body":"Paneles operador, pantallas táctiles y ordenadores industriales robustos",
    "cat.drives.title":"Variadores y drives","cat.drives.body":"Drives AC/DC, servodrives e inversores de frecuencia para motion control",
    "cat.motors.title":"Motores, servos y encoders","cat.motors.body":"Motores industriales, servomotores y encoders para feedback de posición",
    "cat.cnc.title":"CNC y control de movimiento","cat.cnc.body":"Sistemas CNC y tarjetas de control de movimiento para máquinas legacy",
    "cat.safety.title":"Seguridad y equipos de campo","cat.safety.body":"Relés de seguridad, setas de emergencia y sensores industriales de campo",
    "cat.power.title":"Fuentes y componentes de control","cat.power.body":"Fuentes de alimentación, transformadores y componentes de control",
    "cat.all.title":"Explorar todas las categorías","cat.all.body":"Gama completa de repuestos y componentes de automatización",
    "how.title":"Cómo UptimeLegacy te ayuda a evitar paradas",
    "how.intro":"Ante una avería imprevista o planificando obsolescencia, UptimeLegacy es tu punto único para conseguir la pieza adecuada, en el tiempo y condición correctos, protegiendo tu uptime.",
    "how.c1.title":"Sourcing de emergencia para averías","how.c1.body":"Con la línea parada, actuamos rápido. Comparte referencias o sube tu lista: buscamos stock disponible, alternativas compatibles y envío express.",
    "how.c2.title":"Reposición de stock y mantenimiento","how.c2.body":"Construimos la estrategia de repuestos adecuada para tu base instalada: identificamos críticos, cotizamos paquetes y gestionamos reposiciones.",
    "how.c3.title":"Gestión de obsolescencia y ciclo de vida","how.c3.body":"Anticípate al fin de vida: apoyamos last-time-buy, identificamos reemplazos FFF y proponemos rutas de migración cuando sea posible.",
    "how.c4.title":"Opciones de intercambio, reparación y retrofit","how.c4.body":"Extiende la vida de tus activos: unidades de intercambio, refurbished probado o rutas de reparación con partners de confianza.",
    "how.cta":"Saber más sobre cómo ayudamos →",
    "why.title":"Por qué los equipos de mantenimiento eligen UptimeLegacy",
    "why.b1.title":"Enfoque 100% legacy","why.b1.body":"Nos especializamos en automatización industrial obsoleta y legacy, no en MRO generalista. Respuestas más rápidas y opciones realistas cuando el fabricante ya no da soporte.",
    "why.b2.title":"Red global de abastecimiento","why.b2.body":"Buscamos stock en Europa y fuera para localizar piezas difíciles, a menudo con plazos más cortos que el fabricante original.",
    "why.b3.title":"Calidad y garantía","why.b3.body":"Cada pieza se prueba o verifica y cuenta con garantía, con condiciones claras para nuevo, refurbished, intercambio y reparación.",
    "why.b4.title":"Un solo punto de contacto","why.b4.body":"Un equipo gestiona tus RFQs, el sourcing, la logística y el postventa; no necesitas perseguir a múltiples proveedores.",
    "stories.title":"Resultados reales en líneas reales",
    "stories.s1.title":"Tier automoción – fallo en variador legacy","stories.s1.body":"Un fallo en un variador legacy amenazó con parar una línea de automoción varios días. UptimeLegacy localizó una unidad compatible, organizó envío express y ayudó al equipo de mantenimiento a reanudar la producción en 24 horas.",
    "stories.s2.title":"Alimentación y bebidas – PLC obsoleto","stories.s2.body":"Una planta trabajaba con una plataforma PLC obsoleta y poca cobertura de repuestos. Creamos una lista de críticos, suministramos stock e identificamos opciones de migración para reducir el riesgo de paradas.",
    "stories.cta":"Ver más casos →",
    "resources.title":"Recursos para mantenimiento e ingeniería",
    "resources.intro":"Comparte estas guías con mantenimiento, ingeniería y compras para mejorar cómo planificáis y adquirís repuestos para automatización legacy.",
    "res.r1.title":"Guía de repuestos para automatización legacy","res.r1.body":"Cómo identificar componentes críticos, evaluar riesgo y construir la estrategia de repuestos adecuada para sistemas antiguos.","res.r1.cta":"Descargar la guía →",
    "res.r2.title":"Checklist en 5 pasos para obsoletos","res.r2.body":"Lista práctica para agilizar RFQs, comparar ofertas y evitar errores al tratar con componentes obsoletos.","res.r2.cta":"Obtener el checklist →",
    "res.r3.title":"Line Card de UptimeLegacy","res.r3.body":"Resumen de marcas, categorías y servicios disponibles a través de UptimeLegacy.","res.r3.cta":"Solicitar la line card →",
    "insights.title":"Últimos artículos","insights.intro":"Artículos breves y prácticos para ingenieros, responsables de mantenimiento y compradores que trabajan con sistemas legacy.",
    "insights.i1.title":"Cómo reducir el riesgo de parada en PLCs legacy","insights.i1.body":"Muchas plantas aún dependen de plataformas PLC de hace décadas. Pasos clave para proteger tu uptime mientras planificas migraciones.",
    "insights.i2.title":"Entendiendo las condiciones de repuestos","insights.i2.body":"Nuevo, refurbished, intercambio o reparación: diferencias y cómo elegir la opción adecuada para tu necesidad.",
    "insights.i3.title":"Estrategia eficaz de inventario de repuestos legacy","insights.i3.body":"Consejos para equilibrar coste y riesgo al almacenar repuestos para sistemas de automatización envejecidos.",
    "insights.read":"Leer artículo →","insights.all":"Ver todos los artículos →",
    "contact.title":"¿Soporte urgente por un fallo?","contact.p":"Comparte la referencia, sube tu lista o llámanos. Responderemos rápido con disponibilidad, opciones y plazos.","contact.cta1":"Solicitar cotización","contact.cta2":"Llamar al equipo",
    "footer.products":"Productos","footer.p1":"PLCs e I/O","footer.p2":"HMIs y PCs","footer.p3":"Variadores y drives","footer.p4":"Motores y servos","footer.p5":"Controladores CNC","footer.p6":"Equipos de seguridad",
    "footer.brands":"Marcas","footer.resources":"Recursos","footer.r1":"Guías y checklists","footer.r2":"Blog y artículos","footer.r3":"Casos de éxito","footer.r4":"FAQ","footer.r5":"Soporte",
    "footer.company":"Empresa","footer.c1":"Sobre UptimeLegacy","footer.c2":"Contacto","footer.c3":"Política de Privacidad","footer.c4":"Términos y Condiciones","footer.c5":"Política de Cookies",
    "footer.copy":"© 2024 UptimeLegacy. Todos los derechos reservados. | Cero paradas en líneas legacy"
  }
};
